import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <nav>
          <ul className='flex justify-between space-x-8'>
            <li><a href="#" className='text-3xl text-sky-700'>Contact</a></li>
            <li><a href="#" className='text-3xl text-sky-700'>Projects</a></li>
          </ul>
        </nav>

        <h1 className='text-4xl font-extrabold my-6'>
          Welcome to My CV website!
        </h1>

        <p className='text-2xl my-6 font-semibold'>
          Je mappele Abiodun Adepoju, je suis un developpeur web et web mobile et jai 28ans .
        </p>
        <p className='text-2xl'>
          <span className='font-bold'>Project</span> : Trouver un emploi en cdi ou cdd aﬁn dacquerir une experience professionel <br/>
          
        </p>
        <i className='text-lg'>La polyvalence, la rigor, leﬃcacité et la persévérance</i>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Diplomes et formations &rarr;</h2>
            <p>Titre professionnel (RNCP niveau 5) - Developpeur web et web mobile / Via Formation Le Mans, France</p>
            <p>Bac S / Sacred Heart College Nigeria</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Atouts &rarr;</h2>
            <ul>
              <li>Bon sens relationnel</li>
              <li>Travailleur dequipe</li>
              <li>Respecteux</li>
              <li>Discret</li>
              <li>Méthodique</li>
              <li>Rigoreux</li>
              <li>Adaptable</li>
              <li>Ponctuel</li>
              <li>Polyvalent</li>
              <li>Autonome</li>
              <li>Solide culture web</li>
              <li>A lécoute</li>
              <li>Persevearance</li>
              <li>Curieux dapprendre</li>
            </ul>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Compétences &rarr;</h2>
            <ul>
              <li>HTML</li>
              <li>CSS</li>
              <li>Javascript</li>
              <li>Python</li>
              <li>PHP</li>
              <li>jQuery</li>
              <li>React</li>
              <li>React native</li>
              <li>Next.js</li>
              <li>Node.js</li>
              <li>Django</li>
              <li>Django-REST-Framework</li>
              <li>Material UI</li>
              <li>Tailwind CSS</li>
              <li>SQL et MySQL</li>
              <li>Wordpress</li>
              <li>Ajax</li>
            </ul>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Centres dintérêt &rarr;</h2>
            <ul>
              <li>Informatique</li>
              <li>Technologie</li>
              <li>Sport</li>
              <li>Musique</li>
              <li>Voyages</li>
            </ul>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
